create table if not exists COM.CMUSER (
	SYS_DT				DATETIME		NULL		COMMENT '최초등록일시',
	SYS_USER 			VARCHAR(50)		NULL		COMMENT '최초등록유저',
	UPD_DT				DATETIME		NULL		COMMENT '최종수정일시',
	UPD_USER			VARCHAR(50)		NULL		COMMENT '최종수정유저',
    USER_ID				VARCHAR(20)		NOT NULL	COMMENT '유저ID',
    USER_NAME			VARCHAR(50)		NULL		COMMENT '유저명',
    PASSWORD    		VARCHAR(2000)	NULL		COMMENT '비밀번호',
    NON_EXPIRED_YN		BOOLEAN			NOT NULL,
    NON_LOCKED_YN		BOOLEAN			NOT NULL,
    PASS_NON_EXPIRED_YN	BOOLEAN			NOT NULL,
    ENABLED_YN			BOOLEAN			NOT NULL,
	constraint pk_cmuser primary key(USER_ID)
);

create table if not exists COM.CMAUTHORITY (
	SYS_DT				DATETIME		NULL		COMMENT '최초등록일시',
	SYS_USER 			VARCHAR(50)		NULL		COMMENT '최초등록유저',
	UPD_DT				DATETIME		NULL		COMMENT '최종수정일시',
	UPD_USER			VARCHAR(50)		NULL		COMMENT '최종수정유저',
    AUTHORITY_NAME		VARCHAR(50)		NOT NULL	COMMENT '권한명',
    DESCRIPTION			VARCHAR(50)		NULL		COMMENT '권한설명',
	constraint pk_cmauthority primary key(AUTHORITY_NAME)
);



  